error fixed for training
I got this error:
TypeError: `pred` must be a Tensor, or a Python bool, or 1 or 0. Found instead: None
one guy in this 
https://stackoverflow.com/questions/49890823/typeerror-pred-must-be-a-tensor-or-a-python-bool-or-1-or-0-found-instead
suggest changing from none to true